name: Test Workflow

on:
  workflow_dispatch:
     inputs:
        github_ref:
           type: string
           required: false
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Statement
        run: |
          echo " Test workflow. Deploys nothing."
